### ISSUE TITLE
HttpUrlFetcher - Request failed 403: Forbidden

### ISSUE THREAD

**Issue by Hiermur** [TomasValenta/WebCamViewer#40] opened 2015-05-02 10:53 UTC
Hello,

I've tried to add an URL with uppercase characters: 

http://www.besser-bad-harzburg.de/BBHCAM01/Aktuell.jpg

The image is loading in the browser with no problem, but not in WebCam Viewer.

Best reagards, Hiermur

**Comment by TomasValenta** [comment] 2015-05-02 17:26
Hello Hiermur,

thank you for your report! The problem is not with uppercase characters, but with permissions. Log cat show me:

> java.io.IOException: Request failed 403: **Forbidden**

So probably the picture from this server is loaded only when HttpUrlFetcher is identified as Web browser. I want try to fix it. Stay tuned ;)

**Comment by TomasValenta** [comment] 2015-05-06 21:29
Fixed in 3.0 beta2!

**Comment by Hiermur** [comment] 2015-07-03 16:07
It worked in v3.0.0 but in v3.0.1 ist broken again?

**Comment by TomasValenta** [comment] 2015-07-03 19:53
Hi Hiermur,
I am not sure, but it's possible. I need to check the log, but now I am on holiday, so please wait to 19.7. Thank you

**Comment by TomasValenta** [comment] 2015-07-20 10:34
The problem is back,
since I updated Glide from 3.6.0 to 3.6.1 (WCV 3.0.1) and Http user agent is duplicated now (I [reported it](https://github.com/bumptech/glide/issues/546)).
The simple workaround now is return back to 3.6.0. I want to release WCV 3.0.2 soon.

**Closed** 2015-07-24 19:55 UTC
Labels: bug
